from dotenv import load_dotenv
import os
import sqlite3
import pandas as pd
import numpy as np
import sys
from pathlib import Path

# add the private/bot directory to Python's import path
private_path = Path(__file__).resolve().parents[1] / "private" / "bot"
sys.path.insert(0, str(private_path))

from model import SignalEngine   # now you can import normally






"""
This trading bot uses Alpaca to place trades.

The bot is relatively generalisable and functions as follows:

- A single table is used to store assets we are interested in trading.

- Assets have two principle features which determine the decisions we make:

    1. <signal>:            Boolean,   True if we should buy, False if we should sell.
    2. <position_state>:    String,    Collates all information about orders and holdings.

- signal is generated by a private model, although any strategy which can condense into a boolean can be substituted in.

- position_state summarises all possible order and holdings combinations for an asset; possibilities described below.
- NB that this is primarily a long only bot, so short positions are quickly closed if they happen to occur.

- Based entirely off signal and position_state, we can determine whether we should buy, sell, or hold an asset.

POSITION STATE:
_______________________________________
|ORDERS? | HOLDINGS? | POSITION STATE |
|--------|-----------|----------------|
|  NONE  |   NONE    |     CLOSED     |
|--------|-----------|----------------|
|  NONE  |   LONG    |      OPEN      |
|--------|-----------|----------------|
|  NONE  |   SHORT   |     ERROR*     |
|--------|-----------|----------------|
|  LONG  |   NONE    |    OPENING     |
|--------|-----------|----------------|
|  LONG  |   LONG    |  PARTIAL FILL  |
|--------|-----------|----------------|
|  LONG  |   SHORT   |   ERROR FIX*   |
|--------|-----------|----------------|
|  SHORT |   NONE    |     ERROR*     |
|--------|-----------|----------------|
|  SHORT |   LONG    |    CLOSING     |
|--------|-----------|----------------|
|  SHORT |   SHORT   |     ERROR*     |
|--------|-----------|----------------|

- ERRORS*: these should not occur, but could in the case of delayed / unfilled orders, or other unexpected behaviour.
- In these cases, the bot will correct orders and holdings
- There could be cases where we have multiple orders on both sides - depending on the nature of the orders, these can cancel eachother. Otherwise we reconcile cases where we have multiple orders on both sides.


"""
class TradingBot:

    def __init__(self, model_path=None):

        self.signalengine = SignalEngine(refresh_rate=10, model_path=model_path, decision_threshold=0.5)

        print(self.signalengine)
    
    # ======================= #
    # Refresh Holdings Table  #
    # ======================= #
    def refresh_holdings_table_signals(self):
        pass




    # ======================= #
    #     ALPACA METHODS      #
    # ======================= #


    def get_pending_orders(self):
        pass

    def get_open_positions(self):
        pass

    def place_market_order(self):
        pass


    # ======================= #
    # UPDATE POSITION STATES  #
    # ======================= #

    def get_new_asset_position_state(self, ticker, cik):
        """calls get_pending_orders and get_open_positions, and returns a new position state"""
        pass

    def refresh_holdings_table_position_states(self):
        pass


    # =============================== #
    #  RECONCILE ORDERS AND HOLDINGS  #
    # =============================== #
    #  After refreshing position states and signals, as above
    #  these methods place relevant orders to sync position state + signal

    def reconcile_asset_orders_and_holdings(self):
        pass

    def reconcile_table_orders_and_holdings(self):
        pass


    # ======================= #
    #    MAIN LOOP METHODS    #

    def main_loop(self):

        # refresh all position states
        # refresh all signals
        # reconcile all orders and holdings
        # refresh position states again?

        pass